### ISSUE TITLE
Feature Request: config option to disable sound

### ISSUE THREAD

**Issue by mscosti** [Aaronius/hyper-cat#1]
love it! it would be super nice if there was a config option to disable the sound though :)

**Comment by Aaronius** [comment]
👍 I thought that might be the case. :) If you want to take a crack at it, I'd entertain a PR. Otherwise, I'll try to do something about it when I get some time.

**Comment by Aaronius** [comment]
Added in v1.0.0! Just run the command `hyper-cat-toggle-audio`.
