### ISSUE TITLE
Doesn't work on hyper 2.0

### ISSUE THREAD

**Issue by spoike** [Aaronius/hyper-cat#11]
Installing hyper-cat on hyper 2.0 (both stable and canary) doesn't seem to do anything.

There is a warning in the console:
```
Warning: "hyper-cat" plugin uses some deprecated CSS classes (cursor-node).
O.Object.keys.forEach @ bundle.js:1
O @ bundle.js:1
(anonymous) @ bundle.js:1
__webpack_require__ @ bundle.js:1
(anonymous) @ bundle.js:1
__webpack_require__ @ bundle.js:1
(anonymous) @ bundle.js:1
(anonymous) @ bundle.js:1
bundle.js:1 Warning: "hypersixteen" plugin uses some deprecated CSS classes (x-screen).
O.Object.keys.forEach @ bundle.js:1
O @ bundle.js:1
(anonymous) @ bundle.js:1
__webpack_require__ @ bundle.js:1
(anonymous) @ bundle.js:1
__webpack_require__ @ bundle.js:1
(anonymous) @ bundle.js:1
(anonymous) @ bundle.js:1
```

**Comment by drewg233** [comment]
My developer console says this.

`bundle.js:1 TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.
    at Object.componentWillUnmount (/Users/andrewgarcia/.hyper_plugins/node_modules/hyper-cat/index.js:371)`

**Comment by Aaronius** [comment]
🙀 Sorry, folks. Running into issues trying to get it working for Hyper 2. Exhibit A: https://github.com/zeit/hyper/issues/2936

**Comment by borzfele** [comment]
hey, what skills do you need to make it work? :)

**Comment by Aaronius** [comment]
JavaScript and CSS. You're welcome to take shot at it! I have some work-in-progress on the `hyper-2` branch, but I don't know if it's in a very useful state.

**Comment by nodegin** [comment]
I checked out on the `hyper-2` branch but seems not to be working at all..

**Comment by boweihan** [comment]
👍

**Comment by tannert** [comment]
bump!

**Comment by therealrodk** [comment]
+1!  Just discovered this. Would love to see it working! Installed on a new install of Hyper and was disappointed :( It was the only reason I installed Hyper in the first place.

**Comment by philip-ulrich** [comment]
100% agree with the last comment. There was a tweet that sent most of us to hyper because of this plugin

**Comment by pspEgg** [comment]
Download latest Hyper 1 here, it works with this plugin:

https://github.com/zeit/hyper/releases/tag/1.4.7

This is the best thing ever.

**Comment by TristanJMcCormick** [comment]
Nyan bless you all

**Comment by Aaronius** [comment]
I appreciate the enthusiasm to embrace the nyan!

**Comment by marcmend** [comment]
It doesn't woorkkkkk ! Me need !

**Comment by ryansully** [comment]
Is all the recent traffic from @ sdras's tweet?

**Comment by Aaronius** [comment]
Ho ho hooooooooooo! Nyan cat is back with Hyper v2 support! Please open new issues for any problems you run into. Nyan on. 🎉
