### ISSUE TITLE
alwaysActive has no effect

### ISSUE THREAD

**Issue by philip-ulrich** [Aaronius/hyper-cat#12]
I think in the process of fixing hyper-cat for 2.0, the alwaysActive was broken. I have it set to true, but it is not always active. 

On Mac OS 10.14.2.

**Comment by Aaronius** [comment]
Is the nyan cat always toggling when you start typing and stop typing? Could you paste your hyper configuration JSON into this issue? It could be a conflict with another plugin or something. If you'd like, you can put a breakpoint on https://github.com/Aaronius/hyper-cat/blob/75952d4f4ebf7bfaa598e4d688c8bc223d02d47d/index.js#L284 and see if you can pinpoint what's happening. I'm on the same OS as you, so it's a bit surprising that it's not working, but I've been known to write my share of crazy bugs.

**Comment by philip-ulrich** [comment]
Added some prints:
```
      console.log('in setactive');
      console.log(config.alwaysActive);
      if (config.alwaysActive) {
        console.log('always active');
        if (this.state.active) {
          console.log('already active');
          return;
        }

        active = true;
      }
```

Looks like the config is not being set properly in the script somehow.

```
/Users/phil8826/.hyper_plugins/node_modules/hyper-cat/index.js:284 in setactive
/Users/phil8826/.hyper_plugins/node_modules/hyper-cat/index.js:285 false
```


Here is my config file: 
https://gist.github.com/philip-ulrich/18e5a8242311787f074a1510670a6f69

**Comment by JessicaSachs** [comment]
Yeah, confirmed. :-(
This is my only plugin right now.

**Comment by Aaronius** [comment]
I'm having difficulty reproducing your issue, but I just released some changes that could possibly have fixed it for you. The `alwaysActive` option was removed and instead `videoEnabled` and `audioEnabled` configuration options can be tweaked individually. Check out the updated readme and please let me know if the changes help at all. Thanks!

**Comment by philip-ulrich** [comment]
So my issue was that I had the config at the wrong level of the config file. I'm just stupid. 

I do appreciate the new options though. 👍

Unrelated, but an option to control volume of that song would be cool too. 

This issue can be closed from my perspective. Sorry for the runaround I caused.

**Comment by Aaronius** [comment]
Thanks @philip-ulrich.
