### ISSUE TITLE
Bug -> Only backscreen  

### ISSUE THREAD

**Issue by cuduy197** [Aaronius/hyper-cat#3]
I have install plugin , but my hyper have'nt backgound ???
is this a bug?
I'm using win 7
![backscreen](https://cloud.githubusercontent.com/assets/25724956/23819298/da503b1a-0636-11e7-9624-719182d30f61.png)

**Comment by Aaronius** [comment]
Thanks for reporting this. Could you attach your `~/.hyper.js` in a comment?

**Comment by cuduy197** [comment]
@Aaronius  yes, i have
![capture](https://cloud.githubusercontent.com/assets/25724956/23819793/0640b0c2-063e-11e7-89fe-7995b5fb7661.PNG)

**Comment by Aaronius** [comment]
This probably isn't your problem, but it should be `hyper-cat` instead of `hypercat`.

I think the problem is caused by a conflict with one of the other plugins. I'll check it out when I get some time.

**Comment by zachgibson** [comment]
@cuduy197 I had the same issue, removing `"hyperborder"` plugin fixes it.
