### ISSUE TITLE
Scrollbars always created, even if they don't yet exist

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Aaronius/hyper-cat#5]
Before typing:

![image](https://cloud.githubusercontent.com/assets/3335181/24617341/76b2f2b8-1848-11e7-9a6e-1e372d52310e.png)

During typing:

![image](https://cloud.githubusercontent.com/assets/3335181/24617324/6b7cbce4-1848-11e7-9774-f92c65b48012.png)

**Comment by Magneticmagnum** [comment]
Same issue here, Windows 7, hyper v1.3.1

**Comment by Aaronius** [comment]
Will you give v1.0.1 a try and let me know if that fixes it for you?
