### ISSUE TITLE
Support using the plugin as a terminal background

### ISSUE THREAD

**Issue by CarloPalinckx** [Aaronius/hyper-cat#9]
It would be awesome if the plugin could provide a 'background' mode instead of only showing up on keystroke 😺

**Comment by minkezhang** [comment]
For now, you can modify the source directly: https://github.com/Aaronius/hyper-cat/blob/master/index.js#L339.

```
setActive(active) {
  active = true
  ...
```

**Comment by Aaronius** [comment]
Published in v3.1.0 as an `alwaysActive` option.

**Comment by Aaronius** [comment]
I'm not sure it was exactly what you were requesting. It has the same effect as what @cripplet was suggesting though.
